@startuml
'https://plantuml.com/object-diagram
!pragma layout smetana

class Car
class Driver

Car *-- "0..1" Driver

Car : - String make
Car : - String model
Car : - int year
Car : - String bodyStyle
Car : - Driver driver

Car : + Car(String, String, int, String)
Car : + Driver(String, int)
Car : + toString()
Car : + getDriver()
Car : + void setDriver(Driver newDriver)

Driver : - String name
Driver : - int age

Driver : + Driver(String name, int age)
Driver : + String getName()
Driver : + void setName(String name)
Driver : + int getAge()
Driver : + void setAge(int age)
Driver : + String toString()






@enduml
